version = 1

[[analyzers]]
name = "shell"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/IntegerAlex/mergit"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = ["nodejs"]

[[transformers]]
name = "gofmt"